// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using TestProject1;

[TestFixture]
public class LastfmTest : TestBase
{
  private AccountData user = new AccountData("bodyancheq", "FGH-9NA-eWj-XXg");
  private ShoutData shout = new ShoutData("Yakui the Maid is cool, just like Blink-182");
  
  [Test]
  public void lastfmAddShout()
  {
    app.Navigation.OpenHomePage();
    app.Auth.Login(user);
    app.Navigation.OpenMyPage();
    app.Shout.AddShout(shout);
    Thread.Sleep(3000);
    ShoutData newShout = app.Shout.SelectLastShoutData();
    Assert.AreEqual(shout.ShoutText, newShout.ShoutText);
  }
  
  [Test]
  public void lastfmDeleteShout()
  {
    app.Navigation.OpenMyPage();
    app.Shout.DeleteShout();
    Thread.Sleep(3000);
    ShoutData lastShout = app.Shout.SelectLastShoutData();
    Assert.AreNotEqual(shout.ShoutText, lastShout.ShoutText);
  }
  
}
