// // Generated by Selenium IDE
// using System;
// using System.Collections;
// using System.Collections.Generic;
// using System.Linq;
// using System.Threading;
// using OpenQA.Selenium;
// using OpenQA.Selenium.Chrome;
// using OpenQA.Selenium.Firefox;
// using OpenQA.Selenium.Remote;
// using OpenQA.Selenium.Support.UI;
// using OpenQA.Selenium.Interactions;
// using NUnit.Framework;
// [TestFixture]
// public class WegfsDFTest {
//   private IWebDriver driver;
//   public IDictionary<string, object> vars {get; private set;}
//   private IJavaScriptExecutor js;
//   [SetUp]
//   public void SetUp() {
//     driver = new ChromeDriver();
//     js = (IJavaScriptExecutor)driver;
//     vars = new Dictionary<string, object>();
//   }
//   [TearDown]
//   protected void TearDown() {
//     driver.Quit();
//   }
//   [Test]
//   public void wegfsDF() {
//     driver.Navigate().GoToUrl("https://www.last.fm/user/bodyancheq");
//     driver.Manage().Window.Size = new System.Drawing.Size(1280, 783);
//     {
//       var element = driver.FindElement(By.LinkText("Followers"));
//       Actions builder = new Actions(driver);
//       builder.MoveToElement(element).Perform();
//     }
//     {
//       var element = driver.FindElement(By.tagName("body"));
//       Actions builder = new Actions(driver);
//       builder.MoveToElement(element, 0, 0).Perform();
//     }
//     js.ExecuteScript("window.scrollTo(0,2322)");
//     driver.FindElement(By.CssSelector("#\\31 029861194\\3Ashoutbox\\3A f2cbf189-8540-4be2-871c-02d6f7eee375 .shout-more-actions")).Click();
//     driver.FindElement(By.CssSelector("#shout-more-actions-75ca8a79-50ee-4693-a2ba-b16a53721986 .js-delete-shout > .dropdown-menu-clickable-item")).Click();
//     {
//       var element = driver.FindElement(By.CssSelector("#\\31 029861194\\3Ashoutbox\\3A 253e705b-93c5-4065-a464-26b04f3563ae time"));
//       Actions builder = new Actions(driver);
//       builder.MoveToElement(element).Perform();
//     }
//     {
//       var element = driver.FindElement(By.tagName("body"));
//       Actions builder = new Actions(driver);
//       builder.MoveToElement(element, 0, 0).Perform();
//     }
//     driver.FindElement(By.CssSelector(".modal-button > .btn-primary")).Click();
//   }
// }
