// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using TestProject1;

[TestFixture]
public class LastfmTest : TestBase
{
  private AccountData user = new AccountData("bodyancheq", "FGH-9NA-eWj-XXg");
  private ShoutData shout = new ShoutData("Yakui the Maid is cool, just like Blink-182");
  private PlayListData data = new PlayListData("Yooo amogus");
  
  [Test]
  public void lastfmAddShout()
  {
    app.Navigation.OpenHomePage();
    app.Auth.Login(user);
    app.Navigation.OpenMyPage();
    app.Shout.AddShout(shout);
    Thread.Sleep(3000);
    ShoutData newShout = app.Shout.SelectLastShoutData();
    Assert.AreEqual(shout.ShoutText, newShout.ShoutText);
  }
  
  [Test]  
  public void lastfmRenameAlbum()
  {
    app.Navigation.OpenHomePage();
    app.Auth.Login(user);
    app.Navigation.OpenPlaylistPage();
    Thread.Sleep(3000);
    app.Playlist.ChangeName(data);
    Thread.Sleep(3000);
    app.Navigation.OpenPlaylistPage();
    PlayListData newName = app.Playlist.SelectPlayListData();
    Assert.AreEqual(data.PlayListName, newName.PlayListName);
    app.Stop();
  }
}
