// // Generated by Selenium IDE
// using System;
// using System.Collections;
// using System.Collections.Generic;
// using System.Linq;
// using System.Threading;
// using OpenQA.Selenium;
// using OpenQA.Selenium.Chrome;
// using OpenQA.Selenium.Firefox;
// using OpenQA.Selenium.Remote;
// using OpenQA.Selenium.Support.UI;
// using OpenQA.Selenium.Interactions;
// using NUnit.Framework;
// [TestFixture]
// public class Test {
//   private IWebDriver driver;
//   public IDictionary<string, object> vars {get; private set;}
//   private IJavaScriptExecutor js;
//   [SetUp]
//   public void SetUp() {
//     driver = new ChromeDriver();
//     js = (IJavaScriptExecutor)driver;
//     vars = new Dictionary<string, object>();
//   }
//   [TearDown]
//   protected void TearDown() {
//     driver.Quit();
//   }
//   [Test]
//   public void () {
//     driver.Navigate().GoToUrl("https://www.last.fm/user/bodyancheq");
//     driver.Manage().Window.Size = new System.Drawing.Size(1280, 783);
//     driver.FindElement(By.CssSelector(".show-focus-controls > .chartlist-more .disclose-trigger")).Click();
//     driver.FindElement(By.CssSelector("#chartlist-more-f4340bdd-9cd8-4225-b3bb-bdcfa60be4a0 .more-item--delete")).Click();
//   }
// }
